import type { NextPage } from "next";
import Head from "next/head";

const Home: NextPage = () => {
    return (
        <div>
            <Head>
                <title>Create Next App</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <main className="prose ml-12 my-12 ">
                <h1 className="mb-32">
                    Some text to test if styles are working with tailwind 3.2
                </h1>

                <h3>Info</h3>
                <p>
                    If this is not working, check the console. You're
                    probability getting the{" "}
                    <span className="text-orange-500">warning</span>:{" "}
                    <span className="underline">
                        No utility classes were detected in your source files.
                        If this is unexpected, double-check the `content` option
                        in your Tailwind CSS configuration.
                    </span>
                </p>

                <h3> Testing System:</h3>
                <ul>
                    <li>MacBook Air</li>
                    <li>MacOS Monterey</li>
                    <li>Yarn version: 1.22.19</li>
                    <li>NextJS version: 12.3.1</li>
                    <li>React version: 18.2.0</li>
                    <li>React-dom version: 18.2.0</li>
                    <li>Tailwindcss typography version: ^0.5.7 </li>
                    <li>autoprefixer version: ^10.4.12 </li>
                    <li>postcss version: ^8.4.18 </li>
                </ul>

                <h3>
                    Steps to get to this point{" "}
                    <span className="font-normal text-base ">
                        (Used:{" "}
                        <a
                            className="underline underline-offset-2 decoration-sky-500"
                            href="https://nextjs.org/docs/basic-features/typescript"
                        >
                            Nextjs docs
                        </a>
                        ,{" "}
                        <a
                            className="underline underline-offset-2 decoration-sky-500"
                            href="https://tailwindcss.com/docs/guides/nextjs"
                        >
                            tailwind install with nextjs docs
                        </a>
                        ,{" "}
                        <a
                            className="underline underline-offset-2 decoration-sky-500"
                            href="https://tailwindcss.com/docs/typography-plugin"
                        >
                            tailwind typography docs
                        </a>
                        )
                    </span>
                </h3>
                <ol>
                    <li>
                        Create next app:{" "}
                        <span className="underline underline-offset-2 decoration-sky-500">
                            {" "}
                            yarn create next-app --typescript
                        </span>
                    </li>
                    <li>
                        Add dependencies:{" "}
                        <span className="underline underline-offset-2 decoration-sky-500">
                            yarn add -D tailwindcss postcss autoprefixer
                        </span>
                    </li>
                    <li>
                        Generate tailwind.config.js and postcss.config.js:{" "}
                        <span className="underline underline-offset-2 decoration-sky-500">
                            npx tailwindcss init -p
                        </span>
                    </li>
                    <li>Configured paths in tailwind config</li>
                    <li>
                        Add typography plugin:{" "}
                        <span className="underline underline-offset-2 decoration-sky-500">
                            yarn add -D @tailwindcss/typography
                        </span>
                    </li>
                    <li>Add typography plugin to config</li>
                    <li>Add the Tailwind directives to CSS</li>
                    <li>
                        Start the dev server:{" "}
                        <span className="underline underline-offset-2 decoration-sky-500">
                            yarn dev
                        </span>
                    </li>
                    <li>At this point no css was loading</li>
                    <li>
                        Remove .next folder to ensure no cross contamination
                        when testing other version of tailwind
                    </li>
                    <li>
                        Change tailwind version:{" "}
                        <span className="underline underline-offset-2 decoration-sky-500">
                            yarn add -D tailwindcss@3.1.8
                        </span>
                    </li>
                    <li>
                        Start the dev server and see css:{" "}
                        <span className="underline underline-offset-2 decoration-sky-500">
                            yarn dev
                        </span>
                    </li>
                </ol>
            </main>
        </div>
    );
};

export default Home;
